name: mdless # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.0.11' # just for humans, typically '1.2+git' or '1.3.2'
summary: View Markdown comfortably in the terminal # 79 char long summary
description: |
  mdless is a utility that provides a formatted and highlighted view 
  of Markdown files in the terminal.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  mdless:
    # See 'snapcraft plugins'
    plugin: ruby
    source: https://github.com/ttscoff/mdless.git
    source-type: git

apps:
  mdless:
    command: bin/mdless
