name: mdless
base: core18 
version: 1.0.14+snap5
summary: View Markdown comfortably in the terminal
description: |
  mdless is a utility that provides a formatted and highlighted view 
  of Markdown files in the terminal.

grade: stable
confinement: strict 

parts:
  mdless:
    # See 'snapcraft plugins'
    plugin: nil
    source: https://github.com/ttscoff/mdless.git
    source-tag: "1.0.14"
    source-type: git
    override-build: |
      gem build mdless.gemspec
      gem install mdless-*.gem -i $SNAPCRAFT_PART_INSTALL
    build-packages: [gcc, libc6-dev, make, ruby-dev]
    stage-packages: [ruby, git]
  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  #
  # More info: https://forum.snapcraft.io/t/reducing-the-size-of-desktop-snaps/17280#heading--cleanup-part
  #
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - mdless
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core18
    override-prime: |
      set -eux
      for snap in "core18"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

apps:
  mdless:
    plugs:
      - home
      - removable-media
    environment:
      RUBYLIB: $SNAP/usr/lib/ruby/2.5.0:$SNAP/usr/lib/x86_64-linux-gnu/ruby/2.5.0
      GEM_HOME: $SNAP/gems
      GEM_PATH: $SNAP
    command: ruby $SNAP/bin/mdless
